services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      PORT: ${PORT}
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

